name: Publish to NuGet and GitHub Packages

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package-path: ${{ steps.pack.outputs.package-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./src/QuestPDF.Pieces.csproj

      - name: Build the project
        run: dotnet build ./src/QuestPDF.Pieces.csproj --configuration Release

      - name: Pack the NuGet package
        id: pack
        run: |
          dotnet pack ./src/QuestPDF.Pieces.csproj --configuration Release --no-build
          PACKAGE_PATH=$(find ./src/bin/Release -name '*.nupkg' -print -quit)
          echo "package-path=$PACKAGE_PATH" >> $GITHUB_OUTPUT

  publish-nuget:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "${{ needs.build.outputs.package-path }}" \
            --api-key "$NUGET_API_KEY" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

  publish-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push "${{ needs.build.outputs.package-path }}" \
            --api-key "$GITHUB_TOKEN" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --skip-duplicate