name: CI Workflow

on:
  push:
    branches:
      - feature/*  # Trigger on pull requests to branches that start with 'feature/'

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to 'windows-latest' or 'macos-latest' if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out the code from the PR branch

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'  # Use the version of .NET you're working with

    - name: Navigate to project directory
      run: cd tests && ls  # Navigate to the Tests directory and list its contents for debugging

    - name: Build the project
      run: dotnet build  # Builds the project

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal  # Runs the unit tests (no need to rebuild)
